### ISSUE TITLE
Question on scalability of Aho Corasick implementation.

### ISSUE THREAD

**Issue by brownfoxy** [robert-bor/aho-corasick#63] opened 2018-01-03 02:27 UTC
Hi,
  We are using this library for some time now.

Recently there was an OOM due to the increased size of the dictionary. 
A simple test shows that memory usage is linear. (there is no attach screenshot option, sorry!)

Currently, our dictionary size is 0.75 million entries (33 MB csv file each line is a term.)

Trie constructed using this dictionary takes about 1.9GB  (heap entries below)

```
"Class","Objects","Shallow Size","Retained Size"
"java.util.TreeMap","16034426","769652448","2060340624"
"java.util.TreeMap$Entry","16036279","641451160","2060340624"
"org.ahocorasick.trie.Statesun.misc.Launcher$AppClassLoader","15292852","489371264","2060340624"

```

My question is 
1) Is this amount of heap usage normally seen using this library? or is it something unusual?
2) Any general advice on using the library for very big dictionaries (few million entries )?

Thanks in advance,
Phaneendra

**Comment by DaveJarvis** [comment] 2019-08-24 05:34
Is this still an issue with the latest release @brownfoxy ?

**Comment by pnakkala** [comment] 2019-08-25 10:11
I'm not working on that project anymore. So unable to test it. Sorry!

**Comment by brownfoxy** [comment] 2019-08-25 10:12
I'm not working in that project anymore. Unable to test it. Sorry!

**Comment by DaveJarvis** [comment] 2019-08-25 17:11
Closing until the issue is reproduced.

**Closed by DaveJarvis** 2019-08-25 17:11 UTC
